# MySQL (default setup).  Versions 4.1 and 5.0 are recommended.
#
# Get the fast C bindings:
#   gem install mysql
#   (on OS X: gem install mysql -- --include=/usr/local/lib)
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

production:
  adapter: mysql
  database: redmine
  host: localhost
  username: root
  password:
 
development:
  adapter: mysql
  database: redmine_development
  host: localhost
  username: root
  password:
  
development_pgsql:
  adapter: postgresql
  database: redmine
  host: localhost
  username: postgres
  password: "postgres"

development_oracle:
  adapter: oci
  host: 192.168.0.14
  username: rails
  password: "rails"

development_sqlserver:
  adapter: sqlserver
  host: localhost,1157
  database: redmine

test:
  adapter: mysql
  database: redmine_test
  host: localhost
  username: root
  password:

test_pgsql:
  adapter: postgresql
  database: redmine
  host: localhost
  username: postgres
  password: "postgres"

test_oracle:
  adapter: oci
  host: 192.168.0.14
  username: rails_test
  password: "rails"
  
test_sqlserver:
  adapter: sqlserver
  host: localhost,1157
  database: redmine_test
  
demo:
  adapter: sqlite3
  dbfile: db/redmine_demo.db
  
